name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
            -  name: "3.7"
               toxenv: py37
            -  name: "3.8"
               toxenv: py38
            -  name: "3.9"
               toxenv: py39
            -  name: "3.10"
               toxenv: py310
            -  name: "3.8"
               toxenv: flake8

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"
